// ── STORY ITEMS (counters for ending-specific farming) ────────────────────────
const STORY_ITEMS = [
  { id: 'si_btc',          endingId: 'savior',   icon: '₿',  name: 'Physical Bitcoin',          shortName: 'BTC',          max: 40, desc: 'Mechanic wants 40 BTC for Elektronik\'s services. Farm The Lab or craft in Hideout.' },
  { id: 'si_master_kc',    endingId: 'savior',   icon: '🔑', name: 'Master Keycard',             shortName: 'Master KC',    max: 1,  desc: 'Required for the RFID Device quest. Only found inside The Lab — cannot be purchased.' },
  { id: 'si_topo',         endingId: 'debtor',   icon: '🗺️', name: 'Topographic Map',            shortName: 'Topo Map',     max: 5,  desc: 'One per major map: Customs, Woods, Shoreline, Interchange, Reserve. FIR required.' },
  { id: 'si_amulet',       endingId: 'debtor',   icon: '🌙', name: 'Cultist Amulet',             shortName: 'Amulet',       max: 4,  desc: 'Found using Key 314 in marked rooms. Rare. Place in shared room on Lighthouse peninsula.' },
  { id: 'si_dogtag',       endingId: 'debtor',   icon: '🏷️', name: 'PMC Dogtag',                 shortName: 'Dogtag',       max: 100,desc: 'Lightkeeper requires 30 PMC kills in Woods + 100 dogtags. Farm from any PMC in Woods.' },
  { id: 'si_report_folder',endingId: 'survivor', icon: '📁', name: 'Terrible Report Folder',     shortName: 'Report Folder',max: 4,  desc: 'Found in The Lab — inside data rooms. Required for Proper\'s questline (Survivor path).' },
  { id: 'si_repair_kit',   endingId: 'fallen',   icon: '🔧', name: 'Repair Kit (100 durability)', shortName: 'Repair Kit',   max: 40, desc: 'Must be 100 durability. NOT FIR required. Use RBPKTS key for farming.' },
  { id: 'si_mil_component',endingId: 'fallen',   icon: '⚙️', name: 'Military Component',         shortName: 'Mil. Component',max:50, desc: 'Vertex plug, CFDM module, BPX board, etc. NOT FIR. Use RBPKTS key.' },
  { id: 'si_intel_folder', endingId: 'all',      icon: '📋', name: 'Intelligence Folder',        shortName: 'Intel Folder', max: 5,  desc: 'Needed by multiple traders across endings. Can be crafted in the Intelligence Center.' },
];

// ── Story data ─────────────────────────────────────────────────────────────────
// Based on https://escapefromtarkov.fandom.com/wiki/Story_chapters (2025-11)
const STORY_DATA = {

  // Endings — used by path selector
  endings: [
    { id: 'savior',   name: 'SAVIOR',   subtitle: 'The True Ending',   color: '#4caf6e', icon: '🕊️', desc: 'Work with Kerman to expose TerraGroup. The longest path but the best outcome.', requirement: 'Keep the armed case → accept Kerman → RFID keycard at terminal' },
    { id: 'debtor',   name: 'DEBTOR',   subtitle: 'Lightkeeper\'s Path', color: '#d4af37', icon: '🔦', desc: 'Follow Lightkeeper\'s cryptic instructions. Topographic maps, cultist amulets, and a mysterious keycard.', requirement: 'Keep the armed case → reject Kerman → follow Lightkeeper → Lightkeeper keycard at terminal' },
    { id: 'survivor', name: 'SURVIVOR', subtitle: 'Selfish Escape',    color: '#4a8fd4', icon: '🏃', desc: 'Give the case to Proper and pay your way out. Selfish but straightforward.', requirement: 'Deliver armed case to Prapor → Proper\'s path → escape through terminal' },
    { id: 'fallen',   name: 'FALLEN',   subtitle: 'Into the Darkness', color: '#8b6fc4', icon: '🌑', desc: 'Keep the case, reject Kerman, reject Lightkeeper, go back to Proper. The darkest outcome.', requirement: 'Keep case → reject Kerman → reject Lightkeeper → Proper → 40 repair kits + Kappa container' },
  ],

  // All 9 story chapters — shown in the chapter list panel
  shared: [

    // ── 1. Tour ────────────────────────────────────────────────────────────────
    {
      id: 'tour', name: 'Tour', type: 'shared',
      trader: 'Multiple Traders', map: 'Multi-map', levelReq: 1,
      description: 'During the assault on the TerraGroup office, a massive explosion erupted on top of one of the nearby high-rises. I got left on my own, with no contact with command. I\'ll have to handle the evacuation myself. But first things first — get out of Ground Zero.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Tour',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/41/Tour_Icon.png/revision/latest/scale-to-width-down/63?cb=20251121005620',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/00/Tour_Banner.png/revision/latest/scale-to-width-down/320?cb=20251116133623',
      steps: [
        { text: 'Escape Ground Zero' },
        { text: 'Talk to Therapist' },
        { text: 'Ensure access to Streets of Tarkov — hand over 250,000 Roubles to Therapist' },
        { text: '(Optional) Collect the required 250,000 Roubles', optional: true },
        { text: 'Talk to Ragman' },
        { text: 'Survive and extract from Interchange (or visit 3 times)' },
        { text: 'Tell Ragman what you found during the recon' },
        { text: 'Talk to Skier' },
        { text: 'Survive and extract from Customs (or visit 3 times)' },
        { text: 'Hand over any 5 found-in-raid building materials items to Skier' },
        { text: 'Talk to Mechanic' },
        { text: 'Survive and extract from Factory (or visit 3 times)' },
        { text: 'Hand over any 2 found-in-raid weapons to Mechanic' },
        { text: 'Talk to Skier (Woods unlock)' },
        { text: 'Eliminate any 3 targets on Woods' },
        { text: 'Survive and extract from Woods (or visit 3 times)' },
        { text: 'Locate the entrance to the port Terminal' },
        { text: 'Find a way to contact the soldiers at the Terminal' },
        { text: 'Use the intercom to contact the port garrison' },
        { text: 'Learn how to escape Tarkov' },
        { text: 'Ensure access to Reserve — survive and extract from Shoreline + hand over 5 PMC dogtags to Prapor' },
        { text: 'Ensure access to Lighthouse — hand over 20,000 USD to Mechanic' },
        { text: 'Ensure access to The Lab — access the secret TerraGroup facility' },
        { text: '(Optional) Obtain a keycard or access codes to enter The Lab', optional: true },
        { text: '(Optional) Locate the Lab entrance on Factory', optional: true },
        { text: '(Optional) Locate the Lab entrance on Streets of Tarkov', optional: true },
        { text: 'Search the top management offices in The Lab' },
        { text: 'Search the server room in The Lab' },
        { text: 'Locate the escape path through the drainage system in The Lab' },
      ],
      keyItems: [
        { name: 'Roubles', amount: '250,000', fir: false, handover: true },
        { name: 'Any building materials or tools (×5, FIR)', amount: 5, fir: true, handover: true },
        { name: 'Any weapons (×2, FIR)', amount: 2, fir: true, handover: true },
        { name: 'PMC Dogtag (×5)', amount: 5, fir: false, handover: true },
        { name: 'Dollars', amount: '20,000', fir: false, handover: true },
        { name: 'TerraGroup Labs access keycard', amount: 1, fir: false, note: 'Single-use; needed to enter The Lab' },
      ],
    },

    // ── 2. Falling Skies ───────────────────────────────────────────────────────
    {
      id: 'falling_skies', name: 'Falling Skies', type: 'shared',
      trader: 'Prapor', map: 'Woods / Shoreline', levelReq: 1,
      description: 'Mechanic and I got to talking about that plane that went down somewhere in the nature reserve. Nobody really knows what happened to it. I should track it down and take a look — maybe I\'ll find something interesting.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Falling_Skies',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/04/Falling_Skies_Icon.png/revision/latest/scale-to-width-down/50?cb=20251121010306',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/7/7b/Falling_Skies_Banner.png/revision/latest/scale-to-width-down/320?cb=20251116232006',
      steps: [
        { text: 'Locate the fallen plane on the eastern side of Woods' },
        { text: 'Speak to Prapor' },
        { text: 'Reach Loyalty Level 2 with Prapor' },
        { text: 'Ask the traders about the fallen plane (Prapor, Therapist, Skier, Mechanic, Jaeger)' },
        { text: '(Optional) Hand over 2,000 USD to Therapist to learn details about the SUV', optional: true },
        { text: 'Retrieve the flash drive from one of the G-Wagon SUVs (driver side, near Tunnel extract on Shoreline)' },
        { text: 'Hand over the G-Wagon flash drive to Prapor' },
        { text: 'Wait for information from Prapor (~1 hour)' },
        { text: 'Retrieve the plane\'s flight recorder (right side of plane, broken section near back)' },
        { text: 'Leave the flight recorder in the specified spot (destroyed room in house on Shoreline island)' },
        { text: 'Visit Prapor' },
        { text: 'Hand over 3 found-in-raid Rechargeable batteries to Prapor' },
        { text: 'Hand over 5 found-in-raid Printed circuit boards to Prapor' },
        { text: 'Hand over 2 found-in-raid Toolsets to Prapor' },
        { text: 'Wait for information from Prapor (3–5 hours)' },
        { text: 'Retrieve the plane crew\'s transcript from the chairman\'s house on Shoreline' },
        { text: 'Retrieve Elektronik\'s secure flash drive from the chairman\'s house on Shoreline' },
        { text: 'Hand over both items to Prapor' },
        { text: 'Wait for information from Prapor (1–3 hours)' },
        { text: 'Retrieve the armored case (behind cockpit of fallen plane on Woods)' },
        { text: '(Optional) Find Note from Mr. Kerman on pilot seat', optional: true },
        { text: '⚡ KEY CHOICE: Keep the armored case (Savior/Debtor/Fallen paths) OR hand it over to Prapor (Survivor path)', isChoice: true },
      ],
      keyItems: [
        { name: 'G-Wagon flash drive (FIR)', fir: true, handover: true },
        { name: 'Crashed plane\'s flight recorder (FIR)', fir: true },
        { name: 'Rechargeable battery ×3 (FIR)', amount: 3, fir: true, handover: true },
        { name: 'Printed circuit board ×5 (FIR)', amount: 5, fir: true, handover: true },
        { name: 'Toolset ×2 (FIR)', amount: 2, fir: true, handover: true },
        { name: 'Plane crew transcript (FIR)', fir: true, handover: true },
        { name: 'Elektronik\'s secure flash drive (FIR)', fir: true, handover: true },
        { name: 'Armored case (FIR)', fir: true },
        { name: 'Note from Mr. Kerman (FIR, optional)', fir: true, optional: true },
      ],
    },

    // ── 3. Accidental Witness ──────────────────────────────────────────────────
    {
      id: 'accidental_witness', name: 'Accidental Witness', type: 'shared',
      trader: 'Skier', map: 'Customs / Streets / Shoreline', levelReq: 1,
      description: 'Next to the dorms, there\'s a sedan with a threatening message left on it. It seems one of the residents had a serious debt. But this Kozlov was probably not the only debtor in the industrial zone. Perhaps he was being hunted for a reason?',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Accidental_Witness',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/5/5a/Accidental_Witness_Icon.png/revision/latest/scale-to-width-down/64?cb=20251121005249',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/98/Accidental_Witness_Banner.png/revision/latest/scale-to-width-down/320?cb=20251116231814',
      steps: [
        { text: 'Figure out where Kozlov lived — read Note for Kozlov on door of dorm room 110, Customs' },
        { text: 'Find out what Kozlov was involved in — obtain Dorm room 110 key + read Letter from Kozlov\'s room (FIR)' },
        { text: '(Optional) Obtain Note from repair shop (FIR)', optional: true },
        { text: '(Optional) Access Kozlov\'s room', optional: true },
        { text: '(Optional) Investigate Kozlov\'s room', optional: true },
        { text: 'Ask the traders about Anastasia — visit Skier' },
        { text: 'Access Skier\'s accomplice\'s apartment — obtain Zmeisky 3 apartment key (Streets of Tarkov, first floor, backyard side)' },
        { text: '(Optional) Find the key to the apartment', optional: true },
        { text: 'Read 4 documents in apartment: The Ninth Circle #19, Tarkov Herald summary, FSB report, The Ninth Circle #14 (all FIR)' },
        { text: 'Survive and extract from Streets of Tarkov' },
        { text: 'Report to Skier' },
        { text: 'Talk to Ragman' },
        { text: 'Locate Anastasia\'s apartment (second floor, Chekannaya 13 building, Streets of Tarkov)' },
        { text: 'Investigate the entrance of Anastasia\'s building' },
        { text: 'Read: Letter from the mailbox (FIR) + Tarkov Herald newspaper with article by A. Mikhailova (FIR)' },
        { text: 'Locate courier Pasha — search the ambush spot (next to two-story dorms, Customs, near bicycle)' },
        { text: 'Read: Unsealed envelope (FIR)' },
        { text: 'Report to Skier' },
        { text: 'Locate and investigate Reshala\'s stash (bunkhouse on Customs — requires Reshala\'s bunkhouse key)' },
        { text: 'Read 3 notes: Note with an address (FIR), Note with a warning (FIR), Letter from Reshala\'s bunkhouse (FIR)' },
        { text: '(Optional) Locate and neutralize Reshala', optional: true },
        { text: 'Locate Kozlov\'s hideout (house no. 3, eastern part of west village, Shoreline)' },
        { text: 'Obtain Kozlov\'s evidence — Audio tape with incriminating evidence (FIR, in flower bed)' },
        { text: '(Optional) Newspaper clipping with a photo of Anastasia (FIR, inside house on floor)', optional: true },
      ],
      keyItems: [
        { name: 'Note for Kozlov (FIR)', fir: true },
        { name: 'Dorm room 110 key', fir: false },
        { name: 'Zmeisky 3 apartment key', fir: false },
        { name: 'FSB report (FIR)', fir: true },
        { name: 'The Ninth Circle Issue #14 (FIR)', fir: true },
        { name: 'The Ninth Circle Issue #19 (FIR)', fir: true },
        { name: 'Tarkov Herald summary (FIR)', fir: true },
        { name: 'Letter from the mailbox (FIR)', fir: true },
        { name: 'Unsealed envelope (FIR)', fir: true },
        { name: 'Reshala\'s bunkhouse key', fir: false },
        { name: 'Note with an address (FIR)', fir: true },
        { name: 'Note with a warning (FIR)', fir: true },
        { name: 'Letter from Reshala\'s bunkhouse (FIR)', fir: true },
        { name: 'Audio tape with incriminating evidence (FIR)', fir: true },
      ],
    },

    // ── 4. Batya ───────────────────────────────────────────────────────────────
    {
      id: 'batya', name: 'Batya', type: 'shared',
      trader: 'Jaeger / Lightkeeper', map: 'Customs / Reserve / Interchange / Woods / Lighthouse / Shoreline', levelReq: 1,
      description: 'Turns out BEAR didn\'t send just regular squads into Tarkov, there were real SOF guys here. I\'d like to know more about those units and what exactly they were doing.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Batya',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/91/Batya_Icon.png/revision/latest/scale-to-width-down/64?cb=20251121005909',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/97/Batya_Banner.png/revision/latest/scale-to-width-down/320?cb=20251116231842',
      steps: [
        { text: 'Locate and activate the chapter — visit one of: Scav base mattress (Customs) / Radar station radome (Reserve) / Bunker north of health resort (Shoreline) / Mattresses on big rock at USEC camp (Woods)' },
        { text: 'Locate and obtain Bogatyrs patch (FIR) — Customs / Woods / Reserve / Lighthouse' },
        { text: 'Learn more about the Bogatyr squad from the traders — visit Jaeger' },
        { text: 'Locate the Ryabina outpost (north of sawmill, Woods)' },
        { text: 'Find more information — Strelets\' amulet (FIR) + Hostage evacuation report from Voevoda (FIR)' },
        { text: 'Locate the Carousel outpost (opposite IDEA store checkout, ULTRA mall, Interchange)' },
        { text: 'Collect: Taran\'s postcard, Taran\'s personal file, Voevoda\'s audio recorder, Voevoda\'s thoughts audio tape, Voevoda\'s personal file, Strelets\' personal file, Strelets\' note (all FIR)' },
        { text: 'Locate the Gnezdo outpost (east of ULTRA mall, Interchange)' },
        { text: 'Search Gnezdo outpost — Moreman\'s personal file, Bogatyr squad operations report, Map with triangulated signal, BEAR note, First piece of code note, Audio tape with report (all FIR)' },
        { text: 'Locate the ambush spot (near ZB-016 extraction, east of Woods — Moreman\'s grave)' },
        { text: 'Obtain: Second piece of code note (FIR), Moreman\'s phone (FIR), Moreman\'s dogtag (FIR)' },
        { text: 'Retrieve information from Moreman\'s phone — craft Moreman\'s audio tape #1 and #2 at Workbench L1' },
        { text: 'Obtain Intelligence Center level 3' },
        { text: 'Contact the Bogatyr squad — Radio at Intel Center, frequency 35.70, code 27.893.2000' },
        { text: 'Gain access to Lightkeeper (requires Digital secure DSP radio transmitter from Network Provider quest chain)' },
        { text: 'Bring all Bogatyr squad items to Lightkeeper: Taran\'s postcard, Voevoda\'s audio recorder, Strelets\' amulet, Moreman\'s dogtag, Bogatyrs patch' },
        { text: 'Wait for Voevoda to reach out (12–24 hours), then contact via radio (35.70 / 27.893.2000)' },
        { text: 'Complete Voevoda\'s tasks: LMG skill L5, Assault Rifles L10, Stress Resistance L10, Strength L15, kill 15 without dying, kill 4 PMC without dying' },
        { text: 'Contact Voevoda via radio again' },
        { text: 'Locate traces of the traitors — Note mentioning Prapor (FIR, BEAR camp, Lighthouse)' },
        { text: 'Interrogate Prapor — visit Prapor' },
        { text: 'Figure out how cultists connect to the General — Voevoda\'s photo with a cultist mark (FIR, island house Shoreline) + Note mentioning General (FIR)' },
        { text: 'Talk to Lightkeeper' },
        { text: 'Wait for Lightkeeper to prepare documents on The Unheard (12 hours) — pick up Agent network deployment report (FIR)' },
      ],
      keyItems: [
        { name: 'Bogatyrs patch (FIR)', fir: true, handover: true },
        { name: 'Strelets\' amulet (FIR)', fir: true, handover: true },
        { name: 'Hostage evacuation report from Voevoda (FIR)', fir: true },
        { name: 'Taran\'s postcard (FIR)', fir: true, handover: true },
        { name: 'Voevoda\'s audio recorder (FIR)', fir: true, handover: true },
        { name: 'Moreman\'s phone (FIR)', fir: true },
        { name: 'Moreman\'s dogtag (FIR)', fir: true, handover: true },
        { name: 'Moreman\'s audio tape #1 (crafted)', fir: false, note: 'Crafted at Workbench L1 from Moreman\'s phone' },
        { name: 'Moreman\'s audio tape #2 (crafted)', fir: false, note: 'Crafted at Workbench L1' },
        { name: 'Note mentioning Prapor (FIR)', fir: true },
        { name: 'Voevoda\'s photo with a cultist mark (FIR)', fir: true },
        { name: 'Note mentioning General (FIR)', fir: true },
        { name: 'Agent network deployment report (FIR)', fir: true },
      ],
    },

    // ── 5. Blue Fire ───────────────────────────────────────────────────────────
    {
      id: 'blue_fire', name: 'Blue Fire', type: 'shared',
      trader: 'Mechanic', map: 'The Lab / Streets / Woods / Interchange', levelReq: 1,
      description: 'During the raid on the office, some kind of special weapon went off on one of the roofs... I remember a bright blue flash before I blacked out. After that, all the electronics failed. I\'ve never encountered such a powerful EMP weapon before. I need to find out what technology hit the city, and who\'s behind it.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Blue_Fire',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/b/b4/Blue_Fire_Icon.png/revision/latest/scale-to-width-down/51?cb=20251121010338',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/2/2c/Blue_Fire_Banner.png/revision/latest/scale-to-width-down/320?cb=20251116231927',
      steps: [
        { text: 'Activate chapter — pick up and read EMERCOM leaflet or Note by Item #1156 from: shipping container at Scav base (Woods) / tent on Interchange / EMERCOM unit in ULTRA mall / prototype weapon area in The Labyrinth' },
        { text: 'Talk to Mechanic about the EMP blast' },
        { text: '(Optional) Gain access to Mechanic', optional: true },
        { text: 'Locate and obtain Unknown device fragment (FIR) — from LexOs car dealership (Car dealership closed section key) OR Chekannaya 13 apartment (Mysterious room marked key)' },
        { text: 'Hand over the device fragment to Mechanic' },
        { text: 'Plant the Local network hacking device in the server room in The Lab (stash next to office chairs, first floor)' },
        { text: 'Talk to Mechanic' },
        { text: '⚡ KEY CHOICE: Keep the fragment of Item 1156 OR hand it over to Mechanic', isChoice: true },
        { text: 'Find a lead on Item 1156 — Note mentioning Item #1156 (FIR) from Ground Zero office, Lighthouse chalet, or The Lab office O22' },
        { text: 'Investigate the Rus Post office — pick up and listen to 3 audio tapes: 11.05/001, 11.05/002, 11.05/003 (all FIR, Streets of Tarkov post office)' },
        { text: 'Locate the Rus Post Car — Rus Post car key (guaranteed spawn every raid next to back right wheel)' },
        { text: 'Obtain Item #1156 specification (FIR, in back of Rus Post car)' },
      ],
      keyItems: [
        { name: 'Car dealership closed section key (or Mysterious room marked key)', fir: false },
        { name: 'Unknown device fragment (FIR)', fir: true, handover: true },
        { name: 'Local network hacking device (stash item)', fir: false, note: 'Provided by Mechanic via mail or barter' },
        { name: 'Note mentioning Item #1156 (FIR)', fir: true },
        { name: 'Rus Post audio tape 11.05/001 (FIR)', fir: true },
        { name: 'Rus Post audio tape 11.05/002 (FIR)', fir: true },
        { name: 'Rus Post audio tape 11.05/003 (FIR)', fir: true },
        { name: 'Rus Post car key (guaranteed spawn)', fir: false },
        { name: 'Item #1156 specification (FIR)', fir: true },
      ],
    },

    // ── 6. The Labyrinth ───────────────────────────────────────────────────────
    {
      id: 'the_labyrinth', name: 'The Labyrinth', type: 'shared',
      trader: 'Jaeger', map: 'Shoreline / The Labyrinth', levelReq: 1,
      description: 'Even before the raid on the TerraGroup office, I\'d heard about their underground sites in Tarkov. They say that under the coastal Health Resort, a few months back, they found either a bomb shelter or another lab — \'The Labyrinth\'... I should definitely check that place.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Labyrinth_(story_chapter)',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/d/df/The_Labyrinth_Chapter_Icon.png/revision/latest/scale-to-width-down/53?cb=20251121010231',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/93/The_Labyrinth_Chapter_Banner.png/revision/latest/scale-to-width-down/320?cb=20251119000137',
      steps: [
        { text: 'Activate chapter — locate The Labyrinth transit on Shoreline (basement of health resort west wing, requires Knossos LLC facility key)' },
        { text: 'Ask the traders about the underground facility — speak to Jaeger' },
        { text: '(Optional) Ask Therapist how to access the underground facility', optional: true },
        { text: 'Wait for Jaeger to gather the keycards (24–48 hours) — Jaeger provides 2 Labrys access keycards via mail' },
        { text: 'Access the underground facility — enter The Labyrinth via Shoreline transit using Labrys access keycard' },
        { text: 'Locate traces of the BEAR squad — Leshy\'s orders (FIR, food container in front of spawn chamber 2)' },
        { text: 'Investigate the BEAR squad regroup spot at Item 1156 — prototype weapon area' },
        { text: 'Locate the squad leader — torture room' },
        { text: 'Gather more information — Leshy\'s diary (FIR, next to squad leader at torture room)' },
        { text: 'Investigate the 5 lab staff bodies — pick up 5 notes (some require Observation room key)' },
        { text: 'Access the locked Observation room (requires Observation room key)' },
        { text: 'Listen to audio tape — Deceased scientist\'s audio tape (FIR, under scientist\'s right hand)' },
        { text: 'Hand over the audio tape to Jaeger' },
        { text: 'Obtain and read Labyrinth facility research report (FIR, at drain pipe next to pier on Shoreline)' },
      ],
      keyItems: [
        { name: 'Knossos LLC facility key', fir: false, note: 'Required to access transit on Shoreline' },
        { name: 'Labrys access keycard (provided by Jaeger)', fir: false },
        { name: 'Leshy\'s orders (FIR)', fir: true },
        { name: 'Leshy\'s diary (FIR)', fir: true },
        { name: 'Observation room key', fir: false },
        { name: 'Assistant\'s notes on Group #3 (FIR)', fir: true },
        { name: 'Assistant\'s notes on Group #8 (FIR)', fir: true },
        { name: 'Assistant\'s notes on Group #3 and Group #10 (FIR)', fir: true },
        { name: 'Assistant\'s notes on Group #12 (FIR — requires Observation room key)', fir: true },
        { name: 'Assistant\'s notes on TG-Vi-24 test subjects (FIR)', fir: true },
        { name: 'Deceased scientist\'s audio tape (FIR)', fir: true, handover: true },
        { name: 'Labyrinth facility research report (FIR)', fir: true },
      ],
    },

    // ── 7. The Unheard ─────────────────────────────────────────────────────────
    {
      id: 'the_unheard', name: 'The Unheard', type: 'shared',
      trader: 'Mechanic', map: 'Shoreline / The Lab / Streets / Factory', levelReq: 1,
      description: 'I came across a strange note on a TerraGroup sheet. It mentions the will of The Unheard and some fuel needed for \'purification\'. TerraGroup\'s definitely involved in this, and I should gather more information about The Unheard.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Unheard',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/2/2c/The_Unheard_Icon.png/revision/latest?cb=20251121005955',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/8/87/The_Unheard_Banner.png/revision/latest/scale-to-width-down/320?cb=20251121001257',
      steps: [
        { text: 'Activate chapter — pick up and read Note with ramblings about the Purification from TerraGroup security post (Streets) or Ground Zero TerraGroup office no. 4 (TerraGroup science office key)' },
        { text: 'Learn more about TerraGroup\'s activities — Document on changes in enterprise interactions (FIR, The Lab first floor) + Cargo transport fax (FIR, The Lab office O23)' },
        { text: 'Find information about the special catalyst shipment — Transport log with notes (FIR, Factory, on yellow barrel next to hole in floor)' },
        { text: 'Locate Rzhevsky\'s service vehicle — near LexOs car dealership, Streets of Tarkov' },
        { text: 'Obtain his personal belongings — Hard drive from Rzhevsky\'s car (FIR, center console)' },
        { text: 'Retrieve data — craft Hard drive printout at Intelligence Center L1, then read it' },
        { text: 'Read the transcript of Rzhevsky\'s conversation' },
        { text: 'Locate documents on Blue Ice fuel catalyst research — TerraGroup storage room (Factory underground tunnels, TerraGroup storage room keycard)' },
        { text: 'Obtain Fuel catalyst test report (FIR) + Burnt document (FIR) from TerraGroup storage room' },
        { text: 'Search for mention of A.P. in The Lab — locate 1 of 2 whiteboards (O23 or R22) + listen to A.P. meeting audio tape Part 1 (FIR, lecture room stairs) + Part 2 (FIR, lecture room desk)' },
        { text: 'Locate A.P.\'s room in Health Resort — east wing room 305, Shoreline' },
        { text: '(Optional) Find Guard post note (FIR, west wing first floor desk) to confirm room number', optional: true },
        { text: 'Obtain A.P.\'s data storage device — Sliderkey flash drive marked with A.P. (FIR, in laptop on table)' },
        { text: 'Obtain TerraGroup corporate apartment key (FIR, right nightstand in room 305)' },
        { text: '(Optional) Fragment of an unknown document (FIR, left nightstand)', optional: true },
        { text: 'Decrypt the flash drive — craft Decrypted Sliderkey flash drive marked with A.P. at Intelligence Center L1' },
        { text: 'Ask Mechanic for help — visit Mechanic' },
        { text: 'Hand over 5,000,000 Roubles to Mechanic' },
        { text: 'Hand over the Decrypted A.P. flash drive to Mechanic' },
        { text: 'Wait for news from Elektronik (12–24 hours, or 3 hours if Mr. Kerman contacted before)' },
        { text: 'Integrate tech files — craft Reprogrammed keycard for A.P.\'s apartment lock (Green) at Intelligence Center L1' },
        { text: 'Access A.P.\'s corporate apartment (apartment 1, second floor, Cardinal complex, Streets of Tarkov)' },
        { text: 'Access the hidden room using the green keycard' },
        { text: 'Study documents: Order from TerraGroup Worldwide HQ (FIR, on floor), Copy of report for TG Worldwide (FIR, left desk), Document mentioning a protocol (FIR, on pile of documents), Document mentioning the Warden (FIR, right desk)' },
      ],
      keyItems: [
        { name: 'Document on changes in enterprise interactions (FIR)', fir: true },
        { name: 'Cargo transport fax (FIR)', fir: true },
        { name: 'Transport log with notes (FIR)', fir: true },
        { name: 'Hard drive from Rzhevsky\'s car (FIR)', fir: true },
        { name: 'Hard drive printout (crafted at Intel Center L1)', fir: false },
        { name: 'TerraGroup storage room keycard', fir: false },
        { name: 'Fuel catalyst test report (FIR)', fir: true },
        { name: 'Burnt document (FIR)', fir: true },
        { name: 'A.P. meeting audio tape Part 1 (FIR)', fir: true },
        { name: 'A.P. meeting audio tape Part 2 (FIR)', fir: true },
        { name: 'Sliderkey flash drive marked with A.P. (FIR)', fir: true },
        { name: 'TerraGroup corporate apartment key (FIR)', fir: false },
        { name: 'Decrypted Sliderkey flash drive (crafted)', fir: false, handover: true },
        { name: 'Roubles', amount: '5,000,000', fir: false, handover: true },
        { name: 'Reprogrammed keycard for A.P.\'s apartment (Green, crafted)', fir: false },
        { name: 'Order from TerraGroup Worldwide HQ (FIR)', fir: true },
        { name: 'Copy of report for TG Worldwide (FIR)', fir: true },
        { name: 'Document mentioning a protocol (FIR)', fir: true },
        { name: 'Document mentioning the Warden (FIR)', fir: true },
      ],
    },

    // ── 8. They Are Already Here ───────────────────────────────────────────────
    {
      id: 'they_are_here', name: 'They Are Already Here', type: 'shared',
      trader: 'Mechanic', map: 'Lighthouse / Interchange / Streets / Woods / Shoreline', levelReq: 1,
      description: 'I\'ve been seeing strange hooded figures and occult symbols across Tarkov. There\'s an underground cult connected to TerraGroup — the Eye of the World. I should investigate their locations and find out what they\'re planning.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/They_Are_Already_Here',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/9/9e/They_Are_Already_Here_Icon.png/revision/latest/scale-to-width-down/64?cb=20251121005740',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/0/04/They_Are_Already_Here_Banner.png/revision/latest/scale-to-width-down/320?cb=20251116232205',
      steps: [
        { text: 'Activate chapter — pick up Note about the Eye of the World from: Customs dorm 3-story marked room / Reserve marked rooms (RB-BK, RB-VO, or RB-PKPM) / Woods dilapidated village north / Shoreline island house' },
        { text: 'Locate a place connected to the Eye of the World — Cultist\'s torture house on Lighthouse' },
        { text: 'Learn more about the cultist\'s victim — Cult victim audio tape #2 (FIR, on chair in torture house)' },
        { text: 'Locate the cult victim\'s apartment (third floor, old apartment behind Klimov mall, Streets — Cult victim\'s apartment key)' },
        { text: '(Optional) Obtain the key to the apartment (found in torture house on Lighthouse)', optional: true },
        { text: 'Investigate the victim\'s apartment — read Book of the Arrival (FIR) + Note on preparations for the Arrival (FIR) + Cult victim audio tape #1 (FIR)' },
        { text: 'Ask Mechanic about the Eye of the World' },
        { text: '(Optional) Gain access to Mechanic', optional: true },
        { text: 'Locate and neutralize a Cultist priest (any map)' },
        { text: 'Obtain Cultist priest\'s note (FIR) from marked room on Customs, Streets, or Reserve' },
        { text: 'Locate the Eye of the World on Lighthouse — small bedroom, second floor, northern blue chalet' },
        { text: 'Investigate the ransacked cultist room — Victim\'s note (FIR, on adjacent balcony)' },
        { text: '(Optional) Obtain the victim\'s belongings', optional: true },
        { text: 'Locate and obtain Station 14-4 KORD Arshavin K. pass (Damaged) (FIR, on ATV in front of garage opposite chalet)' },
        { text: 'Locate the Eye of the World on Woods — house in dilapidated village north of Woods' },
        { text: 'Investigate the cultists\' house — Newspaper clipping (FIR, whiteboard next to desk)' },
        { text: 'Locate the Eye of the World on Shoreline — red metal shack at radio tower near Road to Customs extraction' },
        { text: 'Repair the Sordi tower — use Toolset inside the shack' },
        { text: 'Learn more about Station 14-4 KORD from Mechanic — visit Mechanic' },
        { text: 'Restore Arshavin\'s keycard — craft Station 14-4 KORD Arshavin K. pass (Restored) at Intelligence Center L1' },
        { text: 'Gain access to NGO Cobalt\'s secret facility — basement of power station on Interchange (swipe Restored pass at keycard panel)' },
        { text: 'Restore power at the station — swipe Restored pass at keycard panel next to entrance door' },
        { text: 'Turn on the cooling system in the server room — flip lever in back of server room (behind grate door)' },
        { text: 'Install Secure Flash drive to download data (stash item) — next to cooling system lever' },
        { text: 'Investigate ARRS Station 14-4 KORD — Mysterious audio tape (FIR, in safe that auto-opens after cooling system on)' },
        { text: 'Survive and extract from Interchange' },
        { text: 'Find a way to disconnect the station — return to facility, read ARRS station mechanic\'s notes (FIR, big desk)' },
        { text: 'Restore the ARRS station to backup settings — press button under table in server room (only 1 player per raid can do this)' },
        { text: 'Collect the Flash drive for ARRS station (FIR, server next to cooling system lever)' },
        { text: 'Survive and extract from Interchange' },
        { text: 'Hand over the flash drive with data to Mechanic' },
        { text: 'Read the ARRS station specifications from the handbook' },
      ],
      keyItems: [
        { name: 'Cult victim\'s apartment key', fir: false, note: 'Found in torture house on Lighthouse (4 spawn locations)' },
        { name: 'Cult victim audio tape #2 (FIR)', fir: true },
        { name: 'Book of the Arrival (FIR)', fir: true },
        { name: 'Note on preparations for the Arrival (FIR)', fir: true },
        { name: 'Cult victim audio tape #1 (FIR)', fir: true },
        { name: 'Cultist priest\'s note (FIR)', fir: true },
        { name: 'Victim\'s note (FIR)', fir: true },
        { name: 'Station 14-4 KORD Arshavin K. pass (Damaged) (FIR)', fir: true },
        { name: 'Newspaper clipping from the cultists\' house (FIR)', fir: true },
        { name: 'Toolset (consumed when repairing Sordi tower)', fir: false },
        { name: 'Programmer\'s note (FIR)', fir: true },
        { name: 'Station 14-4 KORD Arshavin K. pass (Restored) (crafted)', fir: false },
        { name: 'Secure Flash drive (stash item)', fir: false },
        { name: 'Mysterious audio tape (FIR)', fir: true },
        { name: 'ARRS station mechanic\'s notes (FIR)', fir: true },
        { name: 'Flash drive for ARRS station (FIR)', fir: true, handover: true },
      ],
    },

    // ── 9. The Ticket ──────────────────────────────────────────────────────────
    {
      id: 'the_ticket', name: 'The Ticket', type: 'shared',
      trader: 'Mr. Kerman / Mechanic / Lightkeeper', map: 'Streets / Lighthouse / Interchange / The Lab', levelReq: 1,
      description: 'This is the final chapter. The armored case from Falling Skies holds a \'Ticket\' — but unlocking it requires significant resources. Your choices in this chapter determine which ending you reach: Savior, Debtor, Fallen, or Survivor.',
      wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Ticket',
      iconUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/4/4f/The_Ticket_Icon.png/revision/latest/scale-to-width-down/64?cb=20251121010037',
      bannerUrl: 'https://static.wikia.nocookie.net/escapefromtarkov_gamepedia/images/1/19/The_Ticket_Banner.png/revision/latest/scale-to-width-down/320?cb=20251116232109',
      steps: [
        { text: 'Obtain Intelligence Center level 1' },
        { text: 'Talk to Mr. Kerman' },
        { text: 'Wait for Mr. Kerman to reach out' },
        { text: 'Talk to Prapor' },
        { text: 'Talk to Mr. Kerman again' },
        { text: '[If case given to Prapor in Falling Skies]: Locate the camp of Prapor\'s people on Lighthouse and find clues about their intentions' },
        { text: '[If case given to Prapor in Falling Skies]: Talk to Mr. Kerman → Lightkeeper → gain access to Lightkeeper' },
        { text: '[If case given to Prapor in Falling Skies]: Obtain 3 TerraGroup \'Blue Folders\' materials + bring to Lightkeeper' },
        { text: '[If case given to Prapor in Falling Skies]: Launch yellow signal flare at ULTRA\'s main entrance on Interchange + eliminate 15 targets in one raid' },
        { text: 'Unlock the armored case and obtain the \'Ticket\'' },
        { text: 'Ask Mechanic for help — hand over 40 Physical Bitcoin to Mechanic' },
        { text: 'Obtain the Experimental signal jammer' },
        { text: '(Optional) Gain access to The Lab', optional: true },
        { text: 'Collect the RFID card encryption device (Elektronik\'s apartment, Streets of Tarkov — use Elektronik\'s key from Mechanic)' },
        { text: 'Obtain the Black Division keycard (weapon box on ATM in seaport terminal building MS)' },
        { text: '⚡ Access the Terminal loading zone using Black Division keycard in admin building D3', isChoice: true },
      ],
      keyItems: [
        { name: 'Physical Bitcoin ×40 (not FIR required)', amount: 40, fir: false, handover: true, note: 'Payment to Mechanic for Elektronik\'s help' },
        { name: 'Elektronik\'s key (received from Mechanic)', fir: false },
        { name: 'RFID keycard encryption device (FIR, Elektronik\'s apartment)', fir: true },
        { name: 'Black Division keycard (weapon box at ATM, seaport terminal building MS)', fir: false },
      ],
    },

  ], // end shared

  // No per-ending chains needed — The Ticket chapter covers all endings
  chains: { savior: [], debtor: [], survivor: [], fallen: [] },

};
